### ISSUE TITLE
semi option from package.json is ignored

### ISSUE THREAD

**Issue by hjaltisan** [rthor/cra-generate#19]
When setting semi: false in package.json the false value is ignored.
The reason is twofold:
  1 config.js (line 26) always overwrites the value from both defaultOptions and package.json
  2 --no-semi means that if you don't specifically include this option when you use cra-generate (in the command line) the value will be set to semi: true

So reason 2 makes sure that the command line sets the option to true if you don't explicitly set it to false and reason 1 makes sure that the defaultOptions and package.json is ignored completely

**Comment by rthor** [comment]
Ahh good catch! Will fix as soon as I have time. Unless you want to submit a PR 😉

**Comment by hjaltisan** [comment]
Hmm.

The Problem
---
The way I see it this is the order of importance:
1. User explicitly `X` via the cli command
2. `X` is taken from `packages.json`
3. `X` is taken from `defaultOptions` (in `config.js`)

_Given that `X` = whether or not to use semicolons,_
Always take the option from 1, if it doesn't exist there than take the option from 2 and so on.

Solutions?
---
_`use_semicolons`: user specifies via cli that he wants semicolons_
_`skip_semicolons`: user specifies via cli that he doesn't want semicolons_
_`default`: user wants to use the settings from `packages.json` or `defaultOptions`_

### Commander boolean flag options:
1. `option('-s, --semi, 'use semicolons)`
    1. `use_semicolons`: `cra-generate -s demo`
    2. `skip_semicolons`: ... not possible!
    3. `default`: `cra-generate demo`
---
2. `option('--no-semi', 'skip semicolons)`
    1. `use_semicolons`: ... not possible!
    2. `skip_semicolons`: `cra-generate --no-semi demo`
    3. `default`: `cra-generate demo`
---
3. `option('-s, --semi [bool]', 'either true or false')`
    1. `use_semicolons`: `cra-generate -s true demo`
    2. `skip_semicolons`: `cra-generate -s false demo`
    3. `default`: `cra-generate demo`
---
4. `option('-s, --semicolons, 'use semicolons')` and `option('--no-semi', 'skip semicolons')`
    1. `use_semicolons`: `cra-generate -s demo`
    2. `skip_semicolons`: `cra-generate --no-semi demo`
    3. `default`: `cra-generate demo`
---
Issues
---
1. No way to explicitly state that the user doesn't want semicolons
2. No way to explicitly state that the user wants semicolons
3. Solves the problem, but isn't really pretty.
4. Solves the problem, is prettier, but introduces a new issue `cra-generate -s --no-semi demo`...
---
And of course we get the same problem for `-f`...
What solution would you go with?
Or is there some other better solution that I am missing?
The way I see it solution `3` is the best solution, even though it is quite unusual. People are probably used to boolean flags to work like `1` or `2`. But if we go with either of those, then we have to either always ignore `packages.json` or not offer the user to specify all options via cli...

**Comment by rthor** [comment]
I think it would be better to keep certain config values only in `package.json`. F.ex. the semicolon thing is something that you want to set globally for the entire project and you don't want any one component behaving differently. 

Regarding the `--functional` flag. Maybe it should be possible to set a default type in the config, eg `functional/classical` and the explicitly pick a type in the cli tool. Eg

```json 
{
  "craGenerate": {
    "defaultType": "functional",
    "semi": false
  }
}
```
```bash
$ cra-generate --classical FooBar
```
This way, the semicolon thing will be config/default only, and we'll remove it from the flags list. And the functional flag will now adhere to the config/defaults but can be overridden explicitly if need be.
