### ISSUE TITLE
Support creating flow components?

### ISSUE THREAD

**Issue by eirikurn** [rthor/cra-generate#2]
See title.

Guess there are endless options to consider, but this one would "only" need one comment in both js files. Right?

**Comment by rthor** [comment]
If you have a `.flowconfig` in your root, it does this automatically. If you don't, you can tell it explicitly to use flow with `--type-check flow`.

**Comment by rthor** [comment]
I left it out of the docs since the API for it is a bit strange ATM.

**Comment by eirikurn** [comment]
Ok nice! Guess I should create that .flowconfig then :)

**Comment by eirikurn** [comment]
I see it's in the docs now. Happy to close this issue.
